### ISSUE TITLE
Common Dashboard layout

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#105]
[Storybook link](https://dominik-stypula-polcode.github.io/aybolit/?path=/story/cxl-dashboard--cxl-dashboard)

As a user I want to be able to view all my CXL learning content in a central location so I can easily access items that are of importance to me.

## [MVP Dashboard Figma ](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=992%3A9071)

![image](https://user-images.githubusercontent.com/72975440/110332892-3ec05400-8021-11eb-8fc1-c12deb01f1e5.png)

# Specifications

## **Layout**

- [x] Use the story book [layout [layout=2c-r]](https://conversionxl.github.io/aybolit/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cr)
- [x] Use [CXL nav ](https://conversionxl.github.io/aybolit/?path=/story/cxl-ui-cxl-marketing-nav--cxl-marketing-nav)and [footer](sionxl.github.io/aybolit/?path=/story/cxl-ui-footer--cxl-footer-nav) from storybook
- [x] The footer **should not be** "sticky" but be at the bottom of the page.
- [x] Use course/minidegree/playbook accordion cards elements 
- [x] Minidegree and hub cards are always ontop

## Sidebar

- [x] Use the same component that @litll used in the [hub page layout](https://github.com/conversionxl/aybolit/pull/106)
- [x] Only Minidegrees & Playbooks are expandable.
![image](https://user-images.githubusercontent.com/72975440/110324859-d9676580-8016-11eb-8483-5d089512a4af.png)
- [x] The rest of the labels are single level: `Feed`, `Roadmap`, `Courses`, `Review new contributors`
- [x] **Minidegrees** - Include an item for Each minidegree that is selected by the user
- [x] **Playbooks** - Include `Saved Playbooks`, Include an item for Each team you are part of, `My drafts` and `Peer review playbooks`.
- [ ] On mobile view, after selecting an item from the sidebar, the content view is triggered. [Explainer](https://www.loom.com/share/8065bed0a8724db69185f83640132cc8)

## **Tags**

- [x] Tags by default are not selected
- [x] Tags show the number of items in each one
- [x] When clicked filter the content
![image](https://user-images.githubusercontent.com/72975440/110325165-4d097280-8017-11eb-89e0-0a9388eb3db4.png)

**Tags by section**

- [x] In `Feed` the tags are: Playbooks, Courses, Minidegrees
- [x] In `Roadmap` : Include a tag per mini degree, `Started`, `Not started`
- [x] In `Courses` : Include `Started`, `Not started`
- [x] In`Minidegrees` top level: Include `Started`, `Not Started`
- [x] In `Playbooks` top level: include `Drafts`, `Peer review` and `Saved`, include a tag for each team
- [x] In `Playbooks` sub level: Include `Drafts`, `Peer review` and `Saved`

## **Object visibility Logic by section** - to be done when live with database.

- [ ] In `Feed` show last 10 items the user has interacted with
- [ ] In `Roadmap`: Show courses and minidegrees that the user has selected with the roadmap
- [ ] In `Courses`: Show courses the user has selected outside of the roadmap
- [ ] In`Minidegrees`top level: Include `Started` and `Not Started`
- [ ] In `Playbooks`top level: include `Drafts`, `Peer review` and `Saved`, include a tag for each team
- [ ] In 'Playbooks` sub level: Include `Drafts`, `Peer review` and `Saved`

**Comment by dominik-stypula-polcode** [comment]
hi, @heshfekry I wonder why I can't check/uncheck checkboxes on this page (sub-tasks). I remember this worked before, and now not I nor Greg can do it.

**Comment by heshfekry** [comment]
Not sure why that is.

**Comment by dominik-stypula-polcode** [comment]
@hesh, couple of questions regarding last deploy:
https://dominik-stypula-polcode.github.io/aybolit/?path=/story/cxl-dashboard--cxl-dashboard
1) is the current tag display ok in terms of colors, paddings etc. ?
2) should we not display tags if no category is selected?
3) should we apply filtering categories for the demo purpose? One thing important to mention here - probably after WP integration, there won't be filtering in JavaScript but only in PHP/MySQL, for the demo to have it implemented I must do the filtering in JS (because we have only mock JSON data) which is gonna be ultimately removed. 
Filtering by categories and mock the categories data for each category will take some additional time.

**Comment by heshfekry** [comment]
Hi @dominik-stypula-polcode 

1 & 3 . I think the tag / filtering stuff makes more sense to refine once we have live data and QA it in action. 
2 . Forgot to specify, default selection should be on Feed in the sidebar.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry "filtering stuff makes more sense to refine once we have live data and QA it in action" - exactly

**Comment by heshfekry** [comment]
Hi @dominik-stypula-polcode 

1. I would change non selected tag text to a black/grey so its clearer which is selected
2. Forgot to specify, default selection should be on Feed in the sidebar.
3. I think the tag / filtering stuff makes more sense to refine once we have live data and QA it in action. @lkraav thoughts?

**Comment by heshfekry** [comment]
@dominik-stypula-polcode 

I think there are a few items still left to take care of which i will include in the specs (and update the list). Like where to edit the roadmap etc. will do this asap.

**Comment by heshfekry** [comment]
@dominik-stypula-polcode 

- [ ] **Include the correct cards in the correct section**
- Feed - This has all types of cards. Playbooks/hub/course/minidegrees
- Roadmap - minedgree + courses cards
- Courses - course cards
- Minidgree - only course cards
- Playbooks - Playbooks/hub cards
- Review user - ignore for now.

- [ ] Playbooks/mindegree accordion by default is collapsed.
- [ ] Add the study commitment and progress on schedule section.
- [ ] Include "edit" next to study commitment in the top right - This goes to the roadmap edit page
![image](https://user-images.githubusercontent.com/72975440/111130502-91e15c00-8577-11eb-8c35-29ee7271ea73.png)

- [ ] Include the hours from the roadmap and "edit" next to Roadmap title.
![image](https://user-images.githubusercontent.com/72975440/111130740-da991500-8577-11eb-9b3d-ba1717b010bd.png)

- [ ] Include "Add new" next to title on Courses and Minidegrees
![image](https://user-images.githubusercontent.com/72975440/111130672-c6551800-8577-11eb-824a-5626a7cae74e.png)

**Comment by dominik-stypula-polcode** [comment]
hi @heshfekry, should I make specific styling for the text in "blue box"? In the courses card currently, there is nothing like that and it seems it's pulled from the WordPress database as a separate paragraph.
![Screenshot from 2021-03-15 16-25-56](https://user-images.githubusercontent.com/54673942/111178701-b35c3b00-85ab-11eb-8931-2ea3e695cc5f.png)

**Comment by heshfekry** [comment]
Hi @dominik-stypula-polcode 

I would use whatever styling [is already on the cxl accordion card](https://cxl.com/storybook-playbooks/?path=/story/cxl-ui-cxl-vaadin-accordion--cxl-vaadin-accordion-theme-archive)

![image](https://user-images.githubusercontent.com/72975440/111179824-b9065080-85ac-11eb-8405-d471927914c2.png)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry seems like it's just simple paragraph there, nothing specifically styled...
`<p><em>running experiments</em> | <em>customer base studies</em> | <em>prioritization</em></p>`

**Comment by heshfekry** [comment]
Ok, so. keep it as is.

**Comment by dominik-stypula-polcode** [comment]
hi @heshfekry there is a problem using `layout [layout=2c-r]`, visualized on the following video:
https://www.loom.com/share/5510efd4ca7c496c86f3e1e8b61b0c7b
Seems we can't put "MY DASHBOARD" heading in the place like you expect it to be, otherwise it's gonna float like on the video.
Is this what it should be doing?

**Comment by lkraav** [comment]
> Seems we can't put "MY DASHBOARD" heading in the place like you expect it to be, otherwise it's gonna float like on the video.
> Is this what it should be doing?

I hereby veto this layout idea, this is not available in cxl-app-layout

![image](https://user-images.githubusercontent.com/72975440/111130740-da991500-8577-11eb-9b3d-ba1717b010bd.png)

New layout mode be engaged as a separate frontend project, first. For example @anoblet or @freudFlintstone could assess such layout's implementation difficulty if either has availability.

In the meanwhile, @dominik-stypula-polcode, everything stays in regular content panel.

**Comment by heshfekry** [comment]
Okay, the design can be adjusted. Happy to conform to that.

This is specifically related to the extra section at the top right? 
<img width="656" alt="Screenshot 2021-03-16 at 10 24 03" src="https://user-images.githubusercontent.com/72975440/111285778-cb7e9980-8641-11eb-9167-6ad8c706a1b7.png">

If so I can adjust the elements to conform to  `layout [layout=2c-r]`
@lkraav are we still using the `layout [layout=2c-r]` ?

**Comment by dominik-stypula-polcode** [comment]
@heshfekry 
> This is specifically related to the extra section at the top right?
exactly if we remove that and just keep everything below with two separate sections: sidebar + right panel it's not a problem

**Comment by lkraav** [comment]
> Would prefer to avoid an implementation analysis and just stick to what we have.

There may be global benefits to this layout style. Project is worth it, if it can upgrade UX of all sidebar post types, courses etc.

**Comment by heshfekry** [comment]
Okay, we can focus on everything else till we check it.

**Comment by heshfekry** [comment]
@dominik-stypula-polcode [for now till we check the new layout.](https://www.loom.com/share/e46f92f901cb471eabcf949946fad5b3)

**Comment by dominik-stypula-polcode** [comment]
hi @hesh couple of questions regarding the screen you've pasted
https://user-images.githubusercontent.com/72975440/111130502-91e15c00-8577-11eb-8c35-29ee7271ea73.png
1) where is this view in Figma and Storybook (I can't find it).
2) should the right panel look like this in the current version (Courses)?

**Comment by heshfekry** [comment]
Hi @dominik-stypula-polcode that image is just referencing the items that i am pointing at.

1. you don't need it - [refer to this one link in the issue description above.](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=992%3A9071)
2. No what you have now is correct as it resembles the link i just pasted^

**Comment by dominik-stypula-polcode** [comment]
@heshfekry I have also a question about this "Feed - This has all types of cards. Playbooks/hub/course/minidegrees"
I don't currently see the "hub" pages as a category itself (sidebar), so I assume that we should paste some example "hub cards" only for the "Feed/Most Recent" card and nowhere else? 
For hub cards, we operate on this exact view?
![Screenshot from 2021-03-17 12-59-40](https://user-images.githubusercontent.com/54673942/111464116-ad3b9b00-8720-11eb-90a8-c8472c66b1f6.png)

**Comment by heshfekry** [comment]
Hi @dominik-stypula-polcode 

Playbook hub cards are treated similarly to playbook cards. Indeed they don't need their own category in the sidebar.

So they appear in:

- Most recent
- Playbooks - top level
- Saved playbooks
- Team playbooks

**Comment by dominik-stypula-polcode** [comment]
@heshfekry should playbook hubs be always on top of regular playbooks, regardless of the category they're in?

**Comment by heshfekry** [comment]
Yep, hubs and minidegress (black cards) always on top.

**Comment by heshfekry** [comment]
![image](https://user-images.githubusercontent.com/72975440/111467981-5ab0ad80-8725-11eb-951e-8dd02f61b464.png)

This should be inverted. Title on top.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry can you also give me a list of main categories (in the sidebar)  where minidegrees can appear (besides Minidegrees and Most Recent)?

**Comment by heshfekry** [comment]
Should look like this.

Keep `Navigation` for now.

![image](https://user-images.githubusercontent.com/72975440/111468359-bed37180-8725-11eb-8f50-23446117f4bc.png)


Sure minidegrees only appear in `Most recent` and `My Roadmap`

**Comment by dominik-stypula-polcode** [comment]
@heshfekry "Playbooks/mindegree accordion by default is collapsed." - by default accordion remembers its previous state after last user interaction, should I remove this "remembering" when the page is refreshed?

**Comment by heshfekry** [comment]
@dominik-stypula-polcode - ah ok. This is fine. No point messing with it

**Comment by dominik-stypula-polcode** [comment]
@heshfekry just made the last deployment, please let me know if I missed anything from the comments/screens, thanks.

**Comment by heshfekry** [comment]
@dominik-stypula-polcode 

[Check this video for quick feedback](https://www.loom.com/share/34ac43cf5d2f4021963ea80e44e3e52b)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry "how are we working with @litll 's earlier card component work" - this cannot be completely re-used, unfortunately, because Greg's code does not take into account things like category filtering nor tags filtering and is only prepared for the 2 types of cards instead of 4, so I had to make multiple changes in order to possibly not copy/paste the code (stick to the DRY rule as far as possible)

**Comment by heshfekry** [comment]
@dominik-stypula-polcode @litll so what happened to the [common card issue](https://github.com/conversionxl/adeft-blocks/issues/95)?

It was only half complete? I saw that @litll made all of the different cards. Playbook/Course/Hub/Minidegree. Why are we making them again?

**Comment by heshfekry** [comment]
@lkraav @dominik-stypula-polcode @litll

From my basic understanding of the whole rebase/fork workflow. This is the sort of situation it was designed for?

Perhaps this is something for the new dev to solve? seems strange to me the work that greg did on the common card component disappears when we start using those components on another layout.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry actually it did not disappear, but if you dive into the code logic you'll see I had to make some major adjustments/changes just to meet the dashboard requirements, maybe I went too far in avoiding duplication/refactoring, perhaps @lkraav can tell if this could be done other way if he compares our branches.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry regarding the issues: https://dominik-stypula-polcode.github.io/aybolit/?path=/story/cxl-dashboard--cxl-dashboard
I've deployed the code with the latest changes.
Yet I'm still not sure on some details which are in figma, but are not in the layout currently.
1) Counter in the tags: this displays count of items in the specific tag in the specific category right?
Should we add "fake/mock" numbers there or should we skip it? (Implementation for this would probably not worth the effort, since this should be counted by the database query).
![counter-in-tags](https://user-images.githubusercontent.com/54673942/111625172-d9bce900-87ec-11eb-990f-5e8784e1996f.png)
2) mobile cards margin-bottom: I'm not sure (can't find it in any spec) what margin we should make here:
 `--lumo-space-s` or `--lumo-space-m` (so currently I've defined the smaller one).
![margin-between-cards-mobile](https://user-images.githubusercontent.com/54673942/111625434-21dc0b80-87ed-11eb-9008-a4a38a9894ed.png)

**Comment by heshfekry** [comment]
> mobile cards margin-bottom: I'm not sure (can't find it in any spec) what margin we should make here

Use whatever is here https://cxl.com/storybook-playbooks/?path=/story/cxl-ui-cxl-vaadin-accordion--cxl-vaadin-accordion-theme-archive

> Counter in the tags: this displays count of items in the specific tag in the specific category right?
 Should we add "fake/mock" numbers there or should we skip it?

Yes and mock numbers work for now.

Leho will respond regarding rebase/refactoring stuff when he has availability.

**Comment by dominik-stypula-polcode** [comment]
hi @heshfekry on some tags, before the number there is a "pause". Is this a design mistake, or there is a case in which we should display it? Ex. "CXL - 3"

**Comment by heshfekry** [comment]
If by "pause" you mean this:

![image](https://user-images.githubusercontent.com/72975440/111981068-75a96600-8b07-11eb-8d36-7eb6debe1e07.png)

Then we should do this:

![image](https://user-images.githubusercontent.com/72975440/111981117-835eeb80-8b07-11eb-83dc-531355be4905.png)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry I don't actually understand what is the "pause" sign here? Is this a negative number "-3", "-1"? Is this possible we operate on negative numbers here?

**Comment by heshfekry** [comment]
Ah i see. the dash. Skip it.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry yeah, the dash, exactly, sorry for the bad word choosing. Ok cool, thanks.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry https://dominik-stypula-polcode.github.io/aybolit/?path=/story/cxl-dashboard--cxl-dashboard - last deploy is there.
Numbers in **tags** are mocked in the JSON data, so don't mind them (they should be counted by database queries).

**Comment by heshfekry** [comment]
@dominik-stypula-polcode 

And this item?

![image](https://user-images.githubusercontent.com/72975440/111987574-adb4a700-8b0f-11eb-8d50-9dc17361f44a.png)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry thanks for reminding me. Done & deployed.

**Comment by heshfekry** [comment]
@dominik-stypula-polcode @lkraav 

Thanks. I think with Darius you can prepare a Pull request for this issue now.

After that, please proceed to fix the items on the hub page.

**Comment by heshfekry** [comment]
This is issue is now out of date and invalid - discourse
