### ISSUE TITLE
Setup Playbook IDs and Step IDs for pendo.

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#110]
Steps and Playbooks need ID's in the viewer
![image](https://user-images.githubusercontent.com/72975440/112494765-9c73d080-8d83-11eb-8a7f-60f153344459.png)

- [x] **Pendo tagging** - Step ID and WP post ID

**Comment by kylebrodeur** [comment]
We can use a vaadin-button with theme=tertiary. If we are using the same GTM workspace as institute. We will have access to playbook id (page id) in the dataLayer. 

Having the playbook step (or block ID, which should be equal to what's in the editor) as a data attribute would allow us to target specifically and attach feedback.

**Comment by heshfekry** [comment]
@kylebrodeur 

Couple of simple options mentioned by @lkraav for step IDs. Seems enough for MVP implementation.

@litll mentions we already have a low-level step ID implemtation on staging. So should be possible. 

We will address this issue after the refactoring of the adeft-blocks and implemention CXL.com

**Comment by litill** [comment]
@heshfekry Hello there,

Hesh i see that this is output from the staging version, where those front-end facing ids might not got  rendered at all/correctly because that functionality was dropped  but here's a screenshot of what's currently being displayed using the slimmed-down version of the plugin:

![screenshot-nimbus-capture-2021 04 16-15_40_46](https://user-images.githubusercontent.com/36610000/115033803-228abf00-9ecb-11eb-9236-50f22238654a.png)

I just wanted to show you that before Monday -- whatever specific format of those ids (prefix, etc) is needed we can output that based on the things you need.

Thanks,
Greg

**Comment by heshfekry** [comment]
@litill 

Indeed the Unique playbook ID (WP ID) looks to be fine and should work here.

The step ID we need to see how best to deal with them. Not sure if it is ok to keep it as it is, or we need to prefix to avoid issues.

@dominik-stypula-polcode 

This stuff needs to exist in the latest playbook viewer version.

**Comment by litill** [comment]
Hi Hesh, @heshfekry 

The two ids that appear on the step :

one: visible in the non-rendered block, in the WP Admin panel and 
second: visible on the front-end

after a little push from a moment ago are the same. Sorry i didn't notice that the one on the frontend had until now one extra prefix. Now they're the same and come in format:

step-xxxxxxxxxxxx (where xxx is a unique number for this step)

They can be prefixed, too, with the playbook id or formatted any way it's necessary.

The only thing that i might need to add here before Dominik jumps in is that these IDs (unless you need to see them in Storybook too) work independently, they can be added to the wordpress (functioning) version at any time and formatted however it's necessary without the need to reflec those changes in Storybook (unless, of course some extra functionality in Storybook is needed that will take them into account)

**Comment by heshfekry** [comment]
> They can be prefixed, too, with the playbook id or formatted any way it's necessary.

Perhaps the playbook ID prefix is smart. 

so something like `playbook Id - step id`

If this exists in the WordPress version, that is enough. Not sure we need it in storybook at this moment in time. Prefer to finish this item asap and move onto other items.

Let me know when we

**Comment by litill** [comment]
Hi Hesh,

I've sent a pull request to the main branch of cxl-playbook-blocks ( https://github.com/conversionxl/cxl-playbook-blocks/pull/136 )

This pull request changes the storage/output format of the unique steps id to be as follows:

Each step id created from now on will have this format:

playbook-step-xxxx-yyyy

where: xxxx is the WP Post ID (unique) and yyyy is a unique ID of a specific step (the full string will be unique across the whole wordpress)

**Comment by lkraav** [comment]
Seems like https://github.com/conversionxl/cxl-playbook-blocks/pull/136 is the more sensible place to discuss details, since this has nothing to do with UI.
