### ISSUE TITLE
Dashboard QA

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#112]
Link to community
team?

**Comment by lkraav** [comment]
Opening comment reads more like a ClickUp issue, nothing to do with UI component system.

Aside from that, we should probably display recently visited Playbooks in My Dashboard.

**Comment by heshfekry** [comment]
@lkraav this was a placeholder till we saw what came out of the dashboard PR. But there was no movement, so it remained unspecified.

We have a [dashboard design](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=992%3A9071) that takes in feedback from Crowdfunders and Maze tests and an [open PR.](https://github.com/conversionxl/aybolit/pull/109)
