### ISSUE TITLE
vaadin-accordion-panel remains opened on the next page

### ISSUE THREAD

**Issue by tomasced** [conversionxl/aybolit#114]
**Issue:** I opened all jobs on page 1, then selected page 2 and all jobs cards were opened. Jobs list remembers which _vaadin-accordion-panel_ you open: i.e. when you open very top one and very bottom one, _then if you go to another page_, the cards will be opened the same way: top and bottom one.

@saas786 have a look into this.

**Comment by pawelkmpt** [comment]
@saas786 do we have any update regarding this issue? I didn't see any commit

**Comment by pawelkmpt** [comment]
@saas786 https://github.com/conversionxl/jobs-theme/pull/133 did not fix an issue. Code is live on https://cxl.com/jobs/

Is any `aybolit` update necessary? I didn't see any commits.

**Comment by saas786** [comment]
> @saas786 [conversionxl/jobs-theme#133](https://github.com/conversionxl/jobs-theme/pull/133) did not fix an issue. Code is live on https://cxl.com/jobs/
> 
> Is any `aybolit` update necessary? I didn't see any commits.

Not in aybolit.

See: https://github.com/conversionxl/jobs-theme/pull/136

try to manually make a change on site and see if it fixes it, then proceed with merge.

**Comment by lkraav** [comment]
Not this repo's issue.
