### ISSUE TITLE
Accordion panel transparent thumbnail backgrounds are too dark

### ISSUE THREAD

**Issue by martinbon** [conversionxl/aybolit#116]
Original (Background-color contrast at 70pct):
![image](https://user-images.githubusercontent.com/34155711/114575918-51165900-9c83-11eb-8848-c425d8ceaf93.png)

My suggestion(Background-color contrast at 5pct):
![image](https://user-images.githubusercontent.com/34155711/114576024-6d19fa80-9c83-11eb-9ca4-834fc392d527.png)

I don't think we have any accordions that are on black backgrounds. Until then I think it doesn't make sense to have the background as dark as it is right now.

**Comment by lkraav** [comment]
Learning: your commit message missed "fix #116" part @tomasced
