### ISSUE TITLE
Convert "hidden" authors to generic author.

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#119]
----Old------

As an admin I want to hide certain authors from the playbook viewer so that the users only have pertinent information displayed.

Requirements:

- Ability to add and remove users to the list of hidden users
- Author section to be hidden on playbook viewer. But peer review remains
- If users have no account activated, then it is hidden.

![image](https://user-images.githubusercontent.com/72975440/115400195-4743a700-a1e9-11eb-9f1b-847e467c1f45.png)

**Current users to hide:**
1. Verblio
2. Adeft
3. Contentfly
4. If no author because of activation, then author is hidden.

**Comment by litill** [comment]
Hello @heshfekry , i've sent a pull request that would handle points 1-2 but i'm not sure yet what the wordpress status of non-activated user is in the current system, how to handle that. 

@lkraav: Hello Leho, is there a specific way the non-activated users are marked in the current version of the wp ? If so, i'll finish the pull request (https://github.com/conversionxl/cxl-playbook-blocks/pull/144) in a way that is compatible with the system.

@heshfekry: Here's how it looks like in the admin panel: (you can access it now but the actual changes will become functional after the pr is merged)

https://user-images.githubusercontent.com/36610000/116258151-fbf34080-a774-11eb-8420-c6a479854226.mp4

**Comment by litill** [comment]
P.S. The users you've mentioned do not exist in the new WP yet so they're not added to the list on the settings page

**Comment by heshfekry** [comment]
@litill indeed not yet,

Can we check how this functions with the viewer? and if any changes need to be made there.

**Comment by litill** [comment]
@heshfekry Hesh this functionality is a very wordpress specific thing: it can only be simulated in storybook viewer by...not disaplying the author's box. 

But i can show you how it looks locally, in my wordpress:


https://user-images.githubusercontent.com/36610000/116262896-34951900-a779-11eb-9547-6b067a6fe1f8.mp4

**Comment by heshfekry** [comment]
@litill 

Okay, we still need the live playbook viewer to hide the author box associated with these authors. So lets see how we do that exactly via PR or something else?

**Comment by litill** [comment]
Sure, @heshfekry , before posting here, i've made one here: https://github.com/conversionxl/cxl-playbook-blocks/pull/144 . Once i get to know how the inactive users will/are handled i'll add to the request.
