### ISSUE TITLE
Add ID/class to Leave feedback element and Replace Icon.

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#122]
- [x] 1. Add ID/Class

An ID or class on the `Leave feedback` element would be required to ensure quality selection of elements with Pendo. 
Right now it's using :contains text "Report" on a vaadin-button. which can cause conflict with content.

- [x] 2. Replace icon

Replace the` Leave Feedback` icon on this [open PR ](https://github.com/conversionxl/aybolit/pull/115)

![image](https://user-images.githubusercontent.com/72975440/115842016-b30e5580-a41d-11eb-92ef-3314b6db04d0.png)

with  the [vaadin:comment](https://vaadin.com/components/vaadin-icons/html-examples) icon

![image](https://user-images.githubusercontent.com/72975440/115841526-2c597880-a41d-11eb-8f7e-c6db3ec15baa.png)

**Comment by heshfekry** [comment]
@pawelkmpt 

Same deal, if its outside of comfort zone, let me know and I can fix it urgently with @dominik-stypula-polcode next week.

**Comment by pawelkmpt** [comment]
As far as I see "Leave feedback" is currently just in Storybook. I didn't see such line on staging or live site.

Code responsible for that is in Playbooks plugin: https://github.com/conversionxl/cxl-playbook-blocks/blob/main/front/widgets/Actions.php#L34

@lkraav can I edit and push code or you will?

**Comment by lkraav** [comment]
> can I edit and push code or you will?

Do whatever is needed, codebase is stable. 

Just deploy individual file updates for now, if possible.

**Comment by pawelkmpt** [comment]
> > can I edit and push code or you will?
> 
> Do whatever is needed, codebase is stable.
> 
> Just deploy individual file updates for now, if possible.

I edited code on localhost but `vaadin:comment` icon is not visible. We have to import it somehow, right @lkraav ? How?

**Comment by heshfekry** [comment]
@lkraav can we give @pawelkmpt access to https://github.com/conversionxl/vaadin-icons ?

**Comment by lkraav** [comment]
> @lkraav can we give @pawelkmpt access to https://github.com/conversionxl/vaadin-icons ?

It's currently living at https://github.com/lkraav/vaadin-icons/tree/build-subset branch @pawelkmpt

**Comment by pawelkmpt** [comment]
> > @lkraav can we give @pawelkmpt access to https://github.com/conversionxl/vaadin-icons ?
> 
> It's currently living at https://github.com/lkraav/vaadin-icons/tree/build-subset branch @pawelkmpt

I created commit but can't push to the repository. @lkraav can you grant me an access or just simply add this piece of code?

```diff
 const cxlVaadinIconset = [
   'check-circle.svg',
+  'comment.svg',
   'play-circle-o.svg',
   'quote-right.svg',
 ];
```

**Comment by lkraav** [comment]
> I created commit but can't push to the repository. @lkraav can you grant me an access or just simply add this piece of code?

You don't push anything into this vaadin-icons fork. Translate output into Aybolit, as shown in `playbooks` branch https://github.com/conversionxl/aybolit/commit/e1745434eec95984a28136284cb961a90ffd3fbc
