### ISSUE TITLE
Nest a `Leave Feedback` button inside the step accordion

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#123]
As a user I want to click on a button in the step to leave feedback for the playbook team so they can improve the content.

Requirements:

- [x] Button is nested inside accordion underneath the explanation content and is aligned to the left
![image](https://user-images.githubusercontent.com/72975440/116520463-0e838c00-a8d3-11eb-8308-a118c0bf22cb.png)
- [x] Steps without explanation content still show the button when the step-accordion is expanded
- [x] Use the [vaadin:comment](https://vaadin.com/components/vaadin-icons/html-examples) icon before a `Leave feedback`text label 
![image](https://user-images.githubusercontent.com/72975440/115841526-2c597880-a41d-11eb-8f7e-c6db3ec15baa.png)
- [x] Use CXL secondary button element
![image](https://user-images.githubusercontent.com/72975440/116290368-ac703d00-a793-11eb-9bfa-3ad96f0c3318.png)
- [x] Icon should match secodary button text colour

**Comment by heshfekry** [comment]
Hey @pawelkmpt 

Please take a look at this, and if its outside of your comfort zone or too complex. Let me know and we figure it out.

**Comment by pawelkmpt** [comment]
I need an answer to https://github.com/conversionxl/aybolit/issues/122#issuecomment-825573858 first before processing this one

**Comment by heshfekry** [comment]
@pawelkmpt  Yep I saw that, i think i saw this issue previously with something dominik tried. Rating perhaps. Ill dig and see if I can find it.

**Comment by heshfekry** [comment]
@pawelkmpt can we use a placeholder available icon till access comes back?

**Comment by dominik-stypula-polcode** [comment]
hi @heshfekry the deployment by Netlify is here: 
https://comment-hover-icon-plus.netlify.app/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cl
feel free to add some comments below if anything needs fixing

**Comment by heshfekry** [comment]
Looks good,[ just a small interaction fix](https://www.loom.com/share/28e7e1d932cf4b7e8a7e8b66c8447832)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry https://comment-hover-icon-plus.netlify.app/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cl - comment icon click does not trigger the accordion anymore

**Comment by heshfekry** [comment]
Adjusted design to suit @lkraav proposal. 

@dominik-stypula-polcode let's get on this tomorrow first thing. Easily done in less than 1 day.

**Comment by dominik-stypula-polcode** [comment]
https://github.com/conversionxl/aybolit/pull/126

**Comment by lkraav** [comment]
@heshfekry don't close without commit references. If you don't know which commit, not up to you to close. Ping people that know.

**Comment by heshfekry** [comment]
@lkraav no problem, now I know.
