### ISSUE TITLE
lit-2.0.0 stable

### ISSUE THREAD

**Issue by anoblet** [conversionxl/aybolit#124]
Upgrade to lit-2.0.0-rc.1

**Comment by anoblet** [comment]
Storybook is currently broken because of the `instanceOf` check. Justin is working on a fix.

https://lit-and-friends.slack.com/archives/C03PF4L4L/p1619025630249400

**Comment by lkraav** [comment]
@anoblet 3 weeks later, have blockers been fixed upstream perhaps?

**Comment by lkraav** [comment]
https://twitter.com/serhiikulykov/status/1392113831623675904 is good news, we could try upgrading to Lit 2 wholesale.

**Comment by anoblet** [comment]
I looks like Storybook is moving to a new `lit` package rather than updating the `web-component` package. I tried to use it, however I wasn't able to get it running. The readme states that it's still in an experimental phase.

**Comment by anoblet** [comment]
Hopefully some progress:

https://github.com/storybookjs/storybook/pull/14898#issuecomment-843130106

**Comment by lkraav** [comment]
Can we retry with Lit 2 stable now @anoblet?

**Comment by anoblet** [comment]
I'll take a look into it.

**Comment by saas786** [comment]
@lkraav @anoblet I think we can safely close this now, since: https://github.com/conversionxl/aybolit/commit/28f8b1d05846e3b622d58542f869f3c0bfa7e740
