### ISSUE TITLE
Playbooks: move vaadin-checkbox out of `.entry-title`

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#127]
**Problem**: current `.entry-header` structure has display flex glitches when people add multiple elements in accordion panel summary

![image](https://user-images.githubusercontent.com/147228/116667056-66d68e80-a9a4-11eb-8c56-73c0795eaaa1.png)

Source: https://github.com/conversionxl/aybolit/blob/b8131c5eabcf8723ade420e76a88b687303e94a0/packages/storybook/cxl-ui/cxl-vaadin-accordion/cxl-playbook-accordion.story.js#L10-L15

**Maybe better**

Let's attempt without additional wrapper garbage in `.entry-title`, just migrate vaadin-checkbox like:

![image](https://user-images.githubusercontent.com/147228/116666842-1fe89900-a9a4-11eb-9bc0-950c238eecad.png)

**Comment by lkraav** [comment]
Why didn't auto-close work?

@pawelkmpt put "fix <issue>" directly in top commit message line, if there's room.

https://github.com/conversionxl/aybolit/commit/fc01908bf0d3b81dd9ed8126e836cf2827de1c34

**Comment by pawelkmpt** [comment]
> Why didn't auto-close work?

it only closes when PR is merged to main branch

> @pawelkmpt put "fix " directly in top commit message line, if there's room.
> 
> [fc01908](https://github.com/conversionxl/aybolit/commit/fc01908bf0d3b81dd9ed8126e836cf2827de1c34)

you mean edit message and `git push --force` ?

**Comment by lkraav** [comment]
> > Why didn't auto-close work?
> 
> it only closes when PR is merged to main branch

Ahh, mhm.

> you mean edit message and `git push --force` ?

Nah, in future.
