### ISSUE TITLE
cxl-playbook-accordion: empty content steps should hide toggle

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#129]
**PROBLEM**

Notice how step is uncollapsed, but has no content === looks like some error, bad UX.

![image](https://user-images.githubusercontent.com/147228/116675741-d3ef2180-a9ae-11eb-9bba-81f42e59b25b.png)

**SOLUTION**

Can we hide toggle element for empty content steps?

**Comment by heshfekry** [comment]
@lkraav 

This is what i meant about the `leave feedback` button being there. At least there is a purpose to this

**Comment by heshfekry** [comment]
@lkraav 

deploy from dominik: https://comment-hover-icon.netlify.app/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cl

[and PR](https://github.com/conversionxl/aybolit/pull/126)
