### ISSUE TITLE
feat(cxl-ui): cxl-playbook-progress-bar

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#131]
New component

* extends vaadin-progress-bar
* counts progress of playbook vaadin-checkbox checks https://cxl.com/storybook/playbooks/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cl

@dominik-stypula-polcode let us know if you're able to ship this on Monday, first half of day. Otherwise need to assign to someone else that can.

**Comment by lkraav** [comment]
@pawelkmpt are you able to take over?

**Comment by pawelkmpt** [comment]
@lkraav is it still a thing for me or someone else took over?

**Comment by saas786** [comment]
> @lkraav is it still a thing for me or someone else took over?

@pawelkmpt I am looking into this.
