### ISSUE TITLE
Remove red line from explanations and show numbered/bulleted lists

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#137]
**Problem:** 
30-40% of all steps have either numbered lists or bullets inside.

**Solution**

Remove the vertical red line in the step explanation and show numbered/bulleted lists normally.

**Example issues (from first page of playbooks alone):**

https://cxl.com/institute/playbook/use-custom-templates-for-improved-security-performance/
![image](https://user-images.githubusercontent.com/72975440/117637645-4962ab00-b182-11eb-9e57-911d397ee14d.png)
https://cxl.com/institute/playbook/choose-an-analytics-tool/
![image](https://user-images.githubusercontent.com/72975440/117637729-61d2c580-b182-11eb-83b8-85d7c60fe67c.png)
https://cxl.com/institute/playbook/calculate-statistical-significance-for-absolute-difference-in-means/
![image](https://user-images.githubusercontent.com/72975440/117637802-744cff00-b182-11eb-8496-bf4d07ad3c23.png)
https://cxl.com/institute/playbook/create-a-sales-sequence-flow/
![image](https://user-images.githubusercontent.com/72975440/117637873-89299280-b182-11eb-8949-0bbb2f3426f9.png)

**Comment by lkraav** [comment]
Fixed  in https://github.com/conversionxl/aybolit/commit/279335f8ad18d0a5aac9a1ecc58269cf4549c258, deployed live.
