### ISSUE TITLE
Add multistate save/unsave CTA in sidebar on playbook viewer

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#155]
We should also include a save/ unsave icon a text label in the action section located in the sidebar on the playbook viewer. This gives the user the option to save whilst reading, or unsave if the playbook is not relevant anymore.

![image](https://user-images.githubusercontent.com/72975440/121325582-0414d300-c912-11eb-94f6-cef9574b56c0.png)

**Comment by litill** [comment]
@pawelkmpt 
@heshfekry 

Hi Paweł, i just wanted to ask for initial opinion: since the component that needs to be used here is not yet present in Aybolit (asked Dominik) please let me know:

1. is the new wp-rest api endpoint creation for receiving 'stars' the way you'd like to handle this?
2. do you have any preference of how the stars should be saved? initially i though of PODs field on a User
3. Since there are many nice additions on the "integromat branch" that you made and that can be useful for the development of this particular task, could you tell me if the branch is expected to be merged into main soon? That would be very helpful.

Thank you
Greg

**Comment by heshfekry** [comment]
@litill 

Some context this feature is for users to save playbooks to their dashboard. How this is treated in the backend is the goal. No backend decisions have been made on this so far I believe.

1&2 @pawelkmpt is best equipped to anser.

3. absolutely no need for integromat to be involved here. This has nothing to do with anything there. This is a user feature that they use on the platform to save playbooks to their dashboard.

Check the design of the feature here https://app.clickup.com/t/kn7tv7

**Comment by pawelkmpt** [comment]
@litill 

> 1. is the new wp-rest api endpoint creation for receiving 'stars' the way you'd like to handle this?

WDYM by "stars"? Star rating or this "save" feature?

@heshfekry can we call this feature "favourites" or "bookmarks" for clarity?

I think initially just do it with WP_AJAX. It's faster and better for testing.

We might change it later to REST API endpoint, but need to get an opinion from @lkraav.

> 2. do you have any preference of how the stars should be saved? initially i though of PODs field on a User

I think the best is to:

* create new taxonomy: `playbook_bookmarks`
    * it should be hidden from admin UI, public querying and REST API
* every user will have custom term: `user-<user_ID>` eg. `user-12345`
* when user saves the playbook, we assign playbook to the term:
    * `wp_set_object_terms( $playbook_id, 'user-12345', 'playbook_bookmarks', true )` -> last param is critical `$append`
* when user unsaves the playbook, we remove playbook from the term:
    * `wp_remove_object_terms( $playbook_id, 'user-12345', 'playbook_bookmarks' )`

Why?
* it's easy to query for a list of playbooks
* we avoid race condition (if all values would be stored in one option)

> 3. Since there are many nice additions on the "integromat branch" that you made and that can be useful for the development of this particular task, could you tell me if the branch is expected to be merged into main soon? That would be very helpful.

Yes, I will merge it soon. Not sure if today (Friday) or Monday.

**Comment by heshfekry** [comment]
Can we move the discussion to the correct issue https://github.com/conversionxl/cxl-playbook-blocks/issues/187
