### ISSUE TITLE
Add multistate save/unsave icon on playbook cards

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#156]
Saving the playbooks can be done using a simple bookmarking/save icon that alternates between empty and filled. This is how you would save and un save playbooks from any navigation page like hub pages and the dashboard. This gives the user the opportunity to save for later.

To do:

- [x] Save/unsave icon on playbook cards
- [ ] tool tip showing `Save / Unsave Playbook`

![image](https://user-images.githubusercontent.com/72975440/121325035-8fda2f80-c911-11eb-9711-94dc8424f930.png)

**Comment by lkraav** [comment]
Just 2 states?

* Filled star :star: 
* Empty star

**Comment by heshfekry** [comment]
yep, will update the descriptions shortly. the design was done using the shapeup method

**Comment by dominik-stypula-polcode** [comment]
@heshfekry  @anoblet `tool tip showing Save / Unsave Playbook`
Is the "title" attribute like now enough? 
Right now if you hover mouse around the star, you will see the default tooltip "Save playbook" / "Unsave playbook"
https://cxl-save-playbooks.netlify.app/?path=/story/cxl-ui-cxl-vaadin-accordion--cxl-vaadin-accordion-theme-archive

**Comment by heshfekry** [comment]
@dominik-stypula-polcode  This is enough. I will group all the cxl-ui build items together for @lkraav later today
