### ISSUE TITLE
Improve playbook card scannability

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#162]
## Problem
Our users are spending too long going inside and outside of playbooks to find out if they are relevant to them. This causes frustration, drop-off and inconsistent playbook viewed data

## Appetite
Another low-hanging fruit, adding meta data and information we already have and store to the playbook card to make it more scannable. This should be a front-end only task that can be executed in a few days max.

## Solution

- [ ] Remove low-value items from the collapsed card like:
- Level 1 category which is always Marketing 
- and Step count 

- [ ] Add high value items: 
- like breadcrumb information in collapsed card (should be pulled from hub page data). Categories represent level 1 and 2. Level 3-5 are tags. These items are ordered in a specific order, not alphabetically.
- and the steps as a numbered list in expanded card

## Collapsed view - Current playbook cards
![image](https://user-images.githubusercontent.com/72975440/124092173-daedeb00-da56-11eb-9e88-b6d8eee05150.png)

## Collapsed view - Remove low value items like Step count and Level 1 which is always 'Marketing'
![image](https://user-images.githubusercontent.com/72975440/124092189-e04b3580-da56-11eb-8306-71e17bf538b1.png)

## Collapsed view - Add "breadcrumb" under Playbook label and above title.
![image](https://user-images.githubusercontent.com/72975440/124092201-e3462600-da56-11eb-846a-86073cda2007.png)

## Expanded view - Current view
![image](https://user-images.githubusercontent.com/72975440/124092215-e6411680-da56-11eb-9946-fb52fa85808e.png)

## Expanded view - Add steps without explanations as text.
![image](https://user-images.githubusercontent.com/72975440/124092229-e9d49d80-da56-11eb-89f2-59e77a6f92c1.png)

## Rabbit holes

- Playbooks have different number of steps. Just extend vertical height of card. This gives the user an impression of length.
- UI reformating - We can make this work within current card design - Including the save/unsave feature
- Breadcrumb logic - This already exists in hub page setup - discuss with pawel how to pull the data in the correct order.

## no gos

- Interactive features like checkboxes or progress data
- Dont add information from the explanations

**Comment by dominik-stypula-polcode** [comment]
hi @heshfekry deploy for the task is here:
https://improve-playbook-card-scannability.netlify.app/?path=/story/cxl-ui-cxl-vaadin-accordion--cxl-playbook-card
I'm sure from where can I get the "breadcrumbs" data for the playbook card (so mocked for now). 
Screen + link would be helpful.

**Comment by heshfekry** [comment]
So I provided you with 3 different playbooks of different lengths so we can test the view with different amounts of data. Please use those 3. They have the categories underneath.

![image](https://user-images.githubusercontent.com/72975440/124265938-a8b3ba80-db36-11eb-9b65-ce46d9cf4ebc.png)

Please distrubute these 3 versions incl title, use case, category and step content in the view so we can get a better impression.

**Comment by heshfekry** [comment]
For the lest i think looks good.

**Comment by dominik-stypula-polcode** [comment]
@heshfekry https://improve-playbook-card-scannability.netlify.app/?path=/story/cxl-ui-cxl-vaadin-accordion--cxl-playbook-card 
ok so only 3 playbook cards are now visible with the data from docs, for some I didn't found any author in the doc, so mocked author was used. You need anything else there?

**Comment by heshfekry** [comment]
@dominik-stypula-polcode 

Thanks.

I think this looks good. But perhaps having both the breadcrumb and the Level 2 next to playbook is overkill. 

Shall we remove the level 2 from next to **PLAYBOOK** and make the breadcrumb the same colour?

I believe it is `lumo-contrast-50pct: var(--lumo-shade-50pct);`

![image](https://user-images.githubusercontent.com/72975440/124274665-d6523100-db41-11eb-9bd9-feb37320aa8a.png)

**Comment by heshfekry** [comment]
We will end up with this:

![image](https://user-images.githubusercontent.com/72975440/124275272-8cb61600-db42-11eb-8224-31257cc7866d.png)

**Comment by dominik-stypula-polcode** [comment]
@heshfekry deployed on netlify, you can refresh the page

**Comment by heshfekry** [comment]
@dominik-stypula-polcode This looks good.

Ill package this with the other CXL UI builds

**Comment by lkraav** [comment]
With Community launch today @heshfekry can you perhaps scan this repo for open issues and PRs, and see which can be closed?

For this particular issue, I wonder if it's still a thing for our card catalog views in general, such as course catalog on https://cxl.com/institute/

**Comment by heshfekry** [comment]
@lkraav this seems to have been buried in my emails. on it.

This is issue is now out of date - discourse
