### ISSUE TITLE
`cxl:logo` icon

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#17]
With `<cxl-icon-nav-item>` https://github.com/conversionxl/aybolit/pull/10/files#diff-a3ef6e9529d9dcc640bb39f875fdad25R26 arbitratry HTML rendering here would be a complication.

@chanar can you expand our custom icon set w/ CXL logo?

**Comment by chanar** [comment]
So far CXL logo has been html and css. Is there a proper cxl logo svg available?

**Comment by chanar** [comment]
We have cxl-logo component that outputs cxl logo. I might be able to use it in icon nav

**Comment by lkraav** [comment]
Fixed in https://github.com/conversionxl/aybolit/commit/48ff2f803903cb4851e494241ce5a7e48ea1aeb6
