### ISSUE TITLE
Vaadin TreeGrid doesn't work with the current codebase

### ISSUE THREAD

**Issue by dominik-stypula-polcode** [conversionxl/aybolit#173]
I was following the steps from here:
https://vaadin.com/components/vaadin-tree-grid/html-install

Yet I still get following error in the console:

> index.js:49 Unexpected error while loading ./cxl-ui/cxl-vaadin-tree-grid.stories.js: NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry

I've tried to upgrade `cxl-lumo-styles` dependencies to match those from `vaadin-grid`
```
    "@vaadin/vaadin-lumo-styles": "^20.0.4",
    "@vaadin/vaadin-themable-mixin": "^20.0.4"
```

`node_modules` directories were also removed from the project several times and re-installed 
But without effect.

**Comment by lkraav** [comment]
I think we're not compatible with Vaadin 20+ yet. You should try use latest version that's < v20.

**Comment by dominik-stypula-polcode** [comment]
@lkraav currently I see the `^1.*` versions in `cxl-lumo-styles` is that mean we're 19 major versions behind?
```
    "@vaadin/vaadin-lumo-styles": "^1.5.0",
    "@vaadin/vaadin-themable-mixin": "^1.5.2",
```

**Comment by lkraav** [comment]
> @lkraav currently I see the `^1.*` versions in `cxl-lumo-styles` is that mean we're 19 major versions behind?
> 
> ```
>     "@vaadin/vaadin-lumo-styles": "^1.5.0",
>     "@vaadin/vaadin-themable-mixin": "^1.5.2",
> ```

:) sounds unlikely, right?

Vaadin jumped directly from everything lower to v20 and monorepo https://github.com/vaadin/web-components during this year.

**Comment by heshfekry** [comment]
This is issue is now out of date - discourse
