### ISSUE TITLE
`master` vs `develop` vs `playbooks` code split

### ISSUE THREAD

**Issue by pawelkmpt** [conversionxl/aybolit#180]
@saas786 I wanted to work with #66 safe way and firstly merge code splitting into `playbooks` branch, so I can update `cxl-playbook-blocks` before performing main institute plugin/theme updates.

Performing `git merge syed/code-splitting` on `playbooks` branch causes `yarn.lock` conflict which is most likely caused by differences between 2 branches mentioned in the title.

`playbooks` got `master` [merged](https://github.com/conversionxl/aybolit/commit/4eeb04e161e79c88487b44fb892c15715f70f4b1) and have "normalize wheel" set of commits from @anoblet while `develop` does not have it.

So I've tried to do `git rebase master` on `develop` and it also has lots of conflicts which I think would be better solved by you as you know more about necessity of various packages.

What I'd like to achieve is to have 3 title branches in moreless the same state before merging code splitting. Does my thinking make sense or this is not the way you wanted to handle it?

cc @lkraav

**Comment by saas786** [comment]
@pawelkmpt 
You can either merge *develop* or *playbooks* branch onto *master* branch, I will rebase my branch from *master* afterwards so you can merge my PR.

Sounds good?
