### ISSUE TITLE
Use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by pawelkmpt** [conversionxl/aybolit#181]
Google Page Speed insights highlights the following:
![Screenshot 2021-12-10 at 09 06 50](https://user-images.githubusercontent.com/5165721/145539404-8710f528-d679-4cbd-95cf-ea6159f66082.png)

@anoblet do you think we can use passive listeners for scrolling you worked on recently?

* https://web.dev/uses-passive-event-listeners/
* https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#syntax

https://github.com/conversionxl/aybolit/blob/8fd661f6dae993abe4e0b88a7ba935ef68941aea/packages/cxl-ui/src/components/cxl-app-layout.js#L126-L136

**Comment by lkraav** [comment]
What about https://github.com/FrDH/mmenu-js/issues/1256

> > So the performance issue from google lighthouse is misleading and should be ignored?
> correct
