### ISSUE TITLE
Playbook progress bar doesn't work in story: CXL-UI > Paywall > Layout

### ISSUE THREAD

**Issue by saas786** [conversionxl/aybolit#212]
Doesn't work:
https://www.loom.com/share/c5e8a333ef9849ab93d1e373137de73f

Used to work: 
https://www.loom.com/share/ee98dd45b28f422f8926ac7b4d635058

---

I have tested it with:
Before playbooks to master merge: https://github.com/conversionxl/aybolit/commit/7e63abf38a4681000e60fd6303de15dd4cb98911
After & current master: https://github.com/conversionxl/aybolit/commit/6ee74721ca73174739d41dfbb16bbb75093c0d45
~~So its only happening in Lit upgrade branch: https://github.com/conversionxl/aybolit/tree/anoblet/feat/lit~~

---

~~Related PR: https://github.com/conversionxl/aybolit/pull/211~~

---

Updated:

Its not working in `CXL-UI > Paywall > Layout`. So we need to update or sync this story with `CXL-UI > cxl-app-layout > [layout=2c-l]`

**Comment by saas786** [comment]
Related PR: https://github.com/conversionxl/aybolit/pull/211

**Comment by saas786** [comment]
Pulled https://github.com/conversionxl/aybolit/commits/anoblet/feat/lit just now.

Seems like working.

So confused now :)

@anoblet

**Comment by anoblet** [comment]
I believe you are looking at two different stories.

1) CXL-UI > cxl-app-layout > [layout=2c-l]
2) CXL-UI > Paywall > Layout

**Comment by saas786** [comment]
> The paywall story should be updated, though the issue shouldn't be related to the lit migration.

Verified, you are correct. I was mixing both.
I will update the issue description accordingly.

**Comment by saas786** [comment]
Its not working as intended in #213 

For both:

> CXL-UI > cxl-app-layout > [layout=2c-l]
> CXL-UI > Paywall > Layout

**Comment by saas786** [comment]
fixed in: https://github.com/conversionxl/aybolit/commit/cbe266e1f721b551b62b0e1c79b5abaa0e78b4bf
