### ISSUE TITLE
[cxl-tooltip-button]

### ISSUE THREAD

**Issue by anoblet** [conversionxl/aybolit#221]
Should we create a `cxl-tooltip-button` button component who's sole responsibility is to display a tooltip on hover for desktop, and on tap for mobile.

**Comment by anoblet** [comment]
Waiting for `@vaadin/tooltip` to become public: https://discord.com/channels/732335336448852018/774369063454638141/1018952388301824002

**Comment by lkraav** [comment]
I think this is now available upstream, and we usually want it "manually triggered"

https://vaadin.com/docs/latest/components/tooltip/#triggering-manually

![image](https://user-images.githubusercontent.com/147228/208884783-7059bcd6-5fec-434f-8ed6-920043ba7b99.png)
