### ISSUE TITLE
package.json "yarn build" cross platform issue.

### ISSUE THREAD

**Issue by saas786** [conversionxl/aybolit#25]
Ref: https://github.com/conversionxl/aybolit/blob/48ff2f803903cb4851e494241ce5a7e48ea1aeb6/package.json#L13

can we replace

```
"build-styling": "node packages/sass-render/bin/sass-render.js -s 'packages/*/scss/**/*.scss'",
```

with 

```
"build-styling": "node packages/sass-render/bin/sass-render.js -s \"packages/*/scss/**/*.scss\"",
```

does this works on linux as well?

Works on windows if double quotes are used.

**Comment by lkraav** [comment]
Yes, this seems to work on Linux.

I filed https://github.com/web-padawan/aybolit/pull/38 to get this included at upstream.
