### ISSUE TITLE
feat(cxl-ui): cxl-marketing-nav sticky mode

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#29]
Probably use https://github.com/WickyNilliams/headroom.js

**Comment by saas786** [comment]
Original code: https://stackblitz.com/edit/react-headroom-testing

Our current solution: https://stackblitz.com/edit/lit-element-headroom-test-01

I have used `requestAnimationFrame` but it hangs the stackblitz website for me at least.

Do you have any existing "Throttle" code which I can utilize here?

I have my own **spaghetti** throttle function which works in webpack, might not work with esm modules or with @decorators based code etc.

**Comment by lkraav** [comment]
Vaadin uses requestAnimationFrame in several of their components, I've 
noticed. Compare for mistakes maybe?


I have no pre-existing throttle code to share.

**Comment by saas786** [comment]
The reason I went for **rAF** because original React code used it, but I personally use **throttle** or **debounce** with **scroll** & **resize**.

I will look into **Vaadin** components and also will test out my code and see if I still face the issue.

Thanks

**Comment by saas786** [comment]
Implemented 
Ref: https://github.com/conversionxl/aybolit/pull/32

**Comment by lkraav** [comment]
I'm looking to get to reviewing this later today.

In the meanwhile, do you think this implementation can also handle https://github.com/conversionxl/aybolit/issues/30 in one shot, or needs adjustments?

**Comment by lkraav** [comment]
@saas786 this PR can be closed in favor of #32 or what's the plan?
