### ISSUE TITLE
Pricing UI

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#31]
https://www.figma.com/file/Gf1oYUDN3lPXKSd7OCd9VcWh/CXL-Pricing?node-id=35%3A12

![Pricing-03-teams-annual-toggle](https://user-images.githubusercontent.com/147228/70324664-c4f75480-1838-11ea-8916-9ca73f8ef15e.png)

**Comment by paulkirspuu** [comment]
https://i.snipboard.io/DkfFN2.jpg

**Comment by paulkirspuu** [comment]
![image](https://user-images.githubusercontent.com/7458744/70324737-f6702000-1838-11ea-8803-e425c89eb4c4.png)

**Comment by lkraav** [comment]
Initial idea

* `<cxl-institute-pricing-table>`
* "1" is `<vaadin-tabs>`, with page switching, demos available at https://vaadin.com/components/vaadin-tabs/html-examples/tabs-integration-demos
* ^^^^ need to consider mobile UX, I would build that first, even
* business logic stays Gravity Forms in light DOM, need to propose a new form structure - probably needs to be separate forms on different tab pages
* ^^^^ unless someone has a significantly a better non-GF idea + detailed functionality requirements  analysis breakdown (dynamic price calculations etc)
* team size can be regular number control, we don't need to concern ourselves with micro-element fidelity
* ignore currency dropdown

**Comment by lkraav** [comment]
What if... pricing box options we're also vaadin-tabs theme=minimal, horiz scrollable on mobile.

**Comment by tomasced** [comment]
Screenshot of pricing on January 16th (2020):

![image](https://user-images.githubusercontent.com/53396400/72608650-dc435a80-392b-11ea-86a7-727f7290093e.png)

**Comment by lkraav** [comment]
> [Initial idea](https://github.com/conversionxl/aybolit/issues/31#issuecomment-562564974)

We're live. Pretty much zero web components here for now, maybe 20% of "Initial idea" actually made it.

Implementation notes:

* https://gravitywiz.com/documentation/gravity-forms-populate-anything/ nice find by @paulkirspuu this ended up being quite a centerpiece, esp. live merge tags feature
* must exclude /pricing/ from frontend caching, or live merge tags will run into stale security nonces
* product price form fields are populated directly from product post type `_price` meta
* `this_training_id` query param adds a single purchase training price box
* form default display is configurable also via `billing`, `plan` query params, so sales pages could make a choice on what subscription plan to show first
* CSS is mostly inline `style` tag, sitting directly in the page
* ...
