### ISSUE TITLE
Jobs: UI Components

### ISSUE THREAD

**Issue by saas786** [conversionxl/aybolit#35]
**Slack Conversation**
**Syed**: For menu, I should use CXL UI marketing nav component?
**Leho**: Yes. Use everything available in CXL UI first.

**Syed**: Sure, but I don't remember seeing such styling in storybook for cxl ui, like for images showing shadow (as in CXL Jobs Microsite designs)? 

Gallery images on absolute locations (masonry like view) (Home 02-gallery-values.jpg & Job ad-qualifications.jpg) etc. So can you please point me to relevant styles, so I won't code my own css. We can definitely move theme level styles I code to CXL UI, so should I not even bother styling anything in theme to get things going, once done can let you know relevant styles so we can move it to CXL UI?

**Comment by saas786** [comment]
Possible UI Components I can think of, do we have such components already in CXL UI? 
Couple of them I think are there, but we discarded or styles, so not sure if you have coded the improved version or not.

![all-jobs-list](https://user-images.githubusercontent.com/1642796/72502593-830bf600-385b-11ea-9801-6f0f80722708.jpg)

<hr>

![all-jobs-logos](https://user-images.githubusercontent.com/1642796/72502594-83a48c80-385b-11ea-860e-1e10fefeb2d0.jpg)

<hr>

![Home 01-team-mates](https://user-images.githubusercontent.com/1642796/72502595-83a48c80-385b-11ea-8f7e-0db7e3dd66e9.jpg)

<hr>

![Home 01-work-hard-slideshow](https://user-images.githubusercontent.com/1642796/72502598-83a48c80-385b-11ea-8886-57d66d9e741c.jpg)

<hr>

![Home 02-gallery-values](https://user-images.githubusercontent.com/1642796/72502601-843d2300-385b-11ea-8333-7c6e879962cf.jpg)

<hr>

![home-01-locations](https://user-images.githubusercontent.com/1642796/72502603-84d5b980-385b-11ea-87cf-df51f1c6eb51.jpg)

<hr>

![Job ad-qualifications](https://user-images.githubusercontent.com/1642796/72502606-856e5000-385b-11ea-93f2-a50713ad81f0.jpg)

<hr>

![job-ad-sticky-header](https://user-images.githubusercontent.com/1642796/72502607-8606e680-385b-11ea-98d7-6788b5383336.jpg)

**Comment by lkraav** [comment]
@saas786 I inlined-edited your comment directly and added my thoughts.

Long story short, I think only a few card components are worth attending to, but I think UI work should be prioritized last.

First, user flow, functionality and template override requirements is to be established.

Also, maybe you could use something simple like https://wiredjs.com for any placeholder components we are currently missing? Whatever does not complicate the build too much, is fine.

**Comment by saas786** [comment]
![all-jobs-list](https://user-images.githubusercontent.com/1642796/72502593-830bf600-385b-11ea-9801-6f0f80722708.jpg)

@lkraav: looks like `vaadin-accordion-panel theme=reverse` https://vaadin.com/components/vaadin-accordion/html-examples/accordion-theme-variants-demos#reverse-panels

But not sure what the unfold content should be. Maybe this element is missing design, and it should reveal more `.entry-summary` type information before inviting someone to click just based. As-is, it's definitely rather dry cc @jaanmatti 

@saas78: Are we going to use actual Google Map here? or just plain image? If google maps, then are we going to link each Location Card with location pointer? and what it will do upon click?

**Comment by lkraav** [comment]
> Are we going to use actual Google Map here?

Separate issue, priority dead last.

We don't need a background image at all there, to start. Just cards will make the point enough.

**Comment by freudFlintstone** [comment]
As discussed with Syed on slack. Proposed To-Do for Jobs components and styles:
- [ ] cxl-testimonial-card (also in https://github.com/conversionxl/aybolit/issues/49)
- [ ] cxl-office-card (or refactor cxl-testimonial-card into cxl-card and implement theme=testimonial and theme=office)
- [ ] implement accordion list based on `vaadin-accordion-panel theme=reverse` (style only)
- [ ] new nav theme (style only)
- [ ] Job Application form layout (style only) (Jobs/cxl-job-apply.jpg)
- [ ] cxl-job-search, with filters (Jobs/cxl-job-ad-home.jpg)
- [ ] cxl-job-list-pager (Jobs/cxl-job-ad-home.jpg)
- [ ] shadow style class applicable to any element (style only)
- [ ] horizontal image gallery (maybe use vaadin-tabs)


I have just one comment about this one:
![72502607-8606e680-385b-11ea-98d7-6788b5383336](https://user-images.githubusercontent.com/1887825/84429536-b2524380-abfe-11ea-9657-4e5ff1c3d0cf.jpg)

Looks like the sticky header and the "actionable banner" are bsically the same thing. I can make a container element with the _banner_ or _header_ themes. Let me know if it that makes sense and I'll add it to the TODO.

@saas786 Please, validate list items

**Comment by saas786** [comment]
@freudFlintstone 

1) Both have unique container styles

2) Sure, text and button styles are same

3) Sticky header is basically the same when you consider the text, when page is scrolled, sticky header show the content of banner inside the sticky header.

Make sense?

**Comment by freudFlintstone** [comment]
Yes, perfect, I'll rely on existing components as much as possible.
About the banner/header, just so I'm clear, we can use the same component and have different styles, right? My proposed spec:
The cxl-action-banner:
- an optional title slot ("Wordpress developer at Crunchbase" in the header example)
- a list of description items
- a call to action slot

It should be inside a proper <header> element and have width: 100% for the "sticky header" use case. 
It will use the external shadow style for the "banner" use case, without the "title" text.

**Comment by saas786** [comment]
Hmm

Lets create a content slot, it should not concern what data we have inside the banner or inside the sticky header.

Ignore the sticky header and banner for now.

Banner region has same style as many other components, it will just use a simple class like "double-shadow" or such. Nothing special here.

Also ignore the sticky header, nothing special there either.

**Comment by saas786** [comment]
![all-jobs](https://user-images.githubusercontent.com/1642796/85409590-71074f80-b57f-11ea-9394-dc042c4ef10b.jpg)

@lkraav Do we have svg for jobs icon?

@freudFlintstone I can't seem to locate the outline design in UI Compontents, can yo uplease point me to correct markup, which shows vaadin-button with outline design like the above design?

**Comment by freudFlintstone** [comment]
It's not merged yet. LeHo asked me to make some changes, but I couldn't
before. It LL be ready this afternoon (GMT +3)

Em ter, 23 de jun de 2020 10:31, saasfreelancer <notifications@github.com>
escreveu:

**Comment by lkraav** [comment]
> @lkraav Do we have svg for jobs icon?

@saas786 We pick individual icons to add from vaadin-icons, see their demo Examples page.

SVG icon add you can PR yourself. Add a screenshot to PR description for clarity. 

Icon font entry I will help add, since currently nobody else knows the build chain.

**Comment by saas786** [comment]
@lkraav 

Sorry about confusion, I was referring to CXL logo in above screenshot. (CXL careers).

**Comment by lkraav** [comment]
> Sorry about confusion, I was referring to CXL logo in above screenshot. (CXL careers).

Skip this as separate logo. It's old design, we also removed the mini-text line from CXL Institute.

**Comment by tomasced** [comment]
Just logging to GH a message from @freudFlintstone 

> I separated all the elements I had already done into their own branches. Some of them have a copy of the microsite stories with specific changes to apply the correct layout using the styles I added. 
> 
> Here they are:
> 
> 1. horizontal slider for images: https://github.com/freudFlintstone/aybolit/tree/raphael-ui/jobs/components/vaadin-tabs-horizontal-slider
> 2. jobs-listing accordion: https://github.com/freudFlintstone/aybolit/tree/raphael-ui/jobs/components/vaadin-tabs-horizontal-slider
> 3. blockquote and box shadow: https://github.com/freudFlintstone/aybolit/tree/raphael-ui/jobs/components/blockquote-shadow-global
> 4. outlined button styles: https://github.com/freudFlintstone/aybolit/tree/raphael-ui/jobs/components/vaadin-buttom-outlined
> 5. testimonial and office card: https://github.com/freudFlintstone/aybolit/tree/raphael-ui-featured-card
> 
> Like you said yesterday, Syed, app-alyout might not be used, so I didn’t bother working on it with the microsite stories. For the nav bar, we can use cxl-marketing-nav.
> 
> One last note: I’m having an issue with the jobs listing accordion. if you look at my story (CXL UI > cxl-vaadin-accordion > [theme=cxl-jobs-listing]), the proposed design is perfectly reproduced. But that doesn’t happen in the microsite stories. Instead, the h3 style is overwritten. I don’t really understand why, since I don’t have the WP classes here.
> 
> Please don’t use anything from the **raphael-ui-jobs** branch. It’s messy and outdated now

**Comment by freudFlintstone** [comment]
@saas786 Is this setup working for you? If so, I'll open PRs for each of these.

**Comment by saas786** [comment]
> @saas786 Is this setup working for you? If so, I'll open PRs for each of these.

I have refactored it a bit, see my branch for exact code for each component.

**Comment by freudFlintstone** [comment]
> @lkraav: looks like we could have some global theme=shadow rule, so any element could adopt this style - looks like images, list items, etc.

Would this be added to cxl-lumo-styles or cxl-ui? And, if so, how would we go about adding global styles to the cxl-ui package? I'm thinking of a separate export that would only call registerGlobalStyles. Much like cxl-lumo-styles/index.js, but standalone.

**Comment by saas786** [comment]
Job filters using FacetWP:

![job-filters](https://user-images.githubusercontent.com/1642796/87806986-240e5480-c871-11ea-971b-4dbefbf8c75a.jpg)

**Comment by saas786** [comment]
With above filters, I think we can close this issue, unless we find some missing UI element.

**Comment by lkraav** [comment]
Jobs site requirements got simplified and implemented on existing components.
