### ISSUE TITLE
Vaadin Lumo integration and overrides

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#5]
First target: Aybolit Storybook

Implications for every component:

1. must display itself fully themed, stand-alone (=== not inside a layout component, also we may have to display some styled components in some `<iframe>` embed, without any layout... unless even that should have a minimal layout component, or are we moving into a general theme mixin territory here - all layout components must mixin some CXL Lumo component)

2. (?) must explicitly import Lumo https://github.com/vaadin/vaadin-button/blob/v2.1.5/theme/lumo/vaadin-button-styles.html (alternative would be "god object layout component imports Lumo, everybody shares benefits", but that would break 1.)

3. Is it possible to architect Vaadin Lumo style overrides https://github.com/vaadin/vaadin-themable-mixin in a logical Aybolit package structure?

**Comment by chanar** [comment]
1. Hard to understand what's your objective. We can make each component standalone by adding style imports

First import all lumo

```
import '@vaadin/vaadin-lumo-styles/font-icons.js';
import '@vaadin/vaadin-lumo-styles/sizing.js';
import '@vaadin/vaadin-lumo-styles/spacing.js';
import '@vaadin/vaadin-lumo-styles/style.js';
import '@conversionxl/cxl-theme/src/templates/lumo-typography.js';
import '@conversionxl/cxl-theme/src/templates/lumo-colors.js';
```

Then import according to what vaadin components our component is using and which we have additional styles.
```
import '@conversionxl/cxl-theme/src/templates/vaadin-button.js';
import '@conversionxl/cxl-theme/src/templates/vaadin-icons.js';
```
etc.

2. The god object layout came from your request for cxl-marketing layout. Before it was separate package which imports what is now in the beginning of cxl-market-layout component.

3. Actually, I removed vaadin-themable-mixin from all our components and it didn't affect anything. How Vaadin imports it's lumo styles is having theme/lumo/vaadin-lumo-..-styles.js layer which imports lumo style and the component.

```
<link rel="import" href="vaadin-button-styles.html">
<link rel="import" href="../../src/vaadin-button.html">
```

**Comment by chanar** [comment]
2. I don't see anything from with having marketing-bundle.js which you apply for all marketing related landing pages and it works.

**Comment by lkraav** [comment]
`import '@conversionxl/cxl-theme/src/templates/lumo-typography.js';` this is the first :thinking: spot, our custom thinking I want to have vetted by @web-padawan.

**Comment by chanar** [comment]
How I see it currently: importing lumo means importing lumo default styles and variables. If you would like to overwrite the lumo variables then you have to import the styles again as see 

here https://github.com/vaadin/vaadin-lumo-styles/blob/master/color.html
and here https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/src/templates/lumo-colors.js

I'm going to look over the https://github.com/vaadin/vaadin-themable-mixin/wiki and see if there are some new refreshing ideas

**Comment by web-padawan** [comment]
Copying from the message that I also shared in Gitter here.

I have a small script which can help if you want to import some Lumo style modules as they are, without copying the code.

Here is the glitch. It contains 2 parts:

1) Utility helper to get `dom-module` contents and put into css tagged literal accepted by LitElement
https://glitch.com/edit/#!/lumo-css-module?path=lumo-css.js:17:0

2) Example of usage styles getter in LitElement
https://glitch.com/edit/#!/lumo-css-module?path=app.js:9:0

Live demo: https://lumo-css-module.glitch.me

That should be at least helpful anywhere you need to import `typography` and `color` modules only.

**Comment by lkraav** [comment]
If we make a `cxl-lumo-styles` package which

* runs `import @vaadin/vaadin-lumo-styles/all-imports.js`, as is
* implements `<custom-style>` tag with overrides

does https://stackoverflow.com/questions/55768805/polymer-custom-style-does-js-module-loading-order-affect-css-cascade become an issue, or wdyt?

**Comment by lkraav** [comment]
Based on variety of `import` juggling, it became clear it does matter what order things are imported in.

Fortunately, if our override module does `import @vaadin/vaadin-lumo-styles/color.js` + adds our `<custom-style>` overrides, later `import .../color.js` calls do not re-import and our `<custom-style>` rules cascade last.

As far as I can see, this architecture can be trusted. If @web-padawan could confirm, would be helpful.

**Comment by lkraav** [comment]
Next, I wonder if it's sanely possible to have https://github.com/vaadin/vaadin-lumo-styles/tree/master/demo display inside Storybook?

**Comment by lkraav** [comment]
> I have a small script which can help if you want to import some Lumo style modules as they are, without copying the code.

@web-padawan do I understand this script correctly: it's appropriate for mostly only the scenario where Polymer-based Vaadin components are *not* used.

Otherwise I see Vaadin components importing Lumo `<custom-style>`, stylesheet would basically duplicate and cascades would become weird.

This import script could be used to perhaps create a `@aybolit/vaadin-lumo` component set that extends `@aybolit/white-label`, and not so much working directly with Vaadin Polymer components.

Yes, no, maybe?

**Comment by chanar** [comment]
> Next, I wonder if it's sanely possible to have https://github.com/vaadin/vaadin-lumo-styles/tree/master/demo display inside Storybook?

Yes

**Comment by lkraav** [comment]
> > Next, I wonder if it's sanely possible to have https://github.com/vaadin/vaadin-lumo-styles/tree/master/demo display inside Storybook?
> Yes

Copy-pasta, or some clever JS import stuff? 1hr, 8hr, or 40hr project?

**Comment by chanar** [comment]
Hmm, 1-3h. Could use github api https://developer.github.com/v3/repos/contents/ and then extract innerhtml from <body>

**Comment by lkraav** [comment]
Going through GitHub should certainly stay out of it.

Either it works directly from `node_modules/` somehow, or not worth it.

**Comment by chanar** [comment]
Adding a html loader to storybook webpack config might help https://stackoverflow.com/questions/37818401/importing-html-files-with-es6-template-string-loader

**Comment by lkraav** [comment]
> Adding a html loader to storybook webpack config

Maybe related, only from a few days ago by Lit team https://twitter.com/justinfagnani/status/1118384270790332421

**Comment by lkraav** [comment]
Fixed in https://github.com/conversionxl/aybolit/commit/e806c7cd666e83fbcabb67768fb5321298872cd8
