### ISSUE TITLE
Mobile: headlines are too big

### ISSUE THREAD

**Issue by martinbon** [conversionxl/aybolit#55]
After a discussion with CXL Product owner, we thought it would be a simple win, if our headlines on mobile were smaller. Some headlines have long words in them which are awkward to read.

**Current situation example** from iPhone 8 on content-marketing-research online course sales page
![Image](https://user-images.githubusercontent.com/34155711/82330071-03e62480-99eb-11ea-9752-1b86732678f8.png)

NYT example on mobile
![Image](https://user-images.githubusercontent.com/34155711/82330883-0eed8480-99ec-11ea-89c5-9cac47869adc.png)

Here's an example of making:
h1: 2em (main header
h2: 1.5em (in-content headers)
h3: 1.3em (accordion elements)
h4: 1.1em (Course curriculum course title on sales page)
![Image](https://user-images.githubusercontent.com/34155711/82331113-5a079780-99ec-11ea-9c50-c8a9f297c261.png)

The text should probably change with the mobile menu appearing. (around 740px i think)

I did check material.io for their solutions, but I didn't dig too deep. https://material.io/design/typography/the-type-system.html

**Comment by lkraav** [comment]
Please embed images directly into issue body content to avoid lapses in translation accuracy.

**Comment by lkraav** [comment]
Solutions should file a PR with a strategy improvement for https://github.com/conversionxl/aybolit/blob/master/packages/cxl-lumo-styles/scss/typography.scss

Is there a "no media queries" solution available? Less MQs === less complexity, less surprises.
