### ISSUE TITLE
Playbooks: cxl-star-rating should avoid iron-icons import

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#92]
This import is quite heavy https://github.com/PolymerElements/iron-icons/blob/master/iron-icons.js brings in a ton of icons we don't use.

We can get a new icon for our own iconset from vaadin-icons, I can help with this process.
![image](https://user-images.githubusercontent.com/147228/108231233-383d6b80-714a-11eb-9922-6f12af2a3def.png)

But what is a way to avoid importing iron-icons in parent class? Does it mean we have to fork chadweimer/iron-star-rating and assign the dependency our fork on GH?

cc @dominik-stypula-polcode

**Comment by dominik-stypula-polcode** [comment]
@lkraav yes, the simplest way would be to fork it, or just copy the whole class as `IronStarRatingBase` to the CXL-UI, change it and build `CXLStarRating` upon it. I think the author pulled the whole icon set because the user can choose which icon he wants to set in place of default `icons:star`
```
icon: {
              type: String,
              value: 'icons:star'
          }
```

**Comment by lkraav** [comment]
> yes, the simplest way would be to fork it,

Cool, I forked it, and invited you with Write access. We then update our component with `npm i github:conversionxl/iron-star-rating`

When Vaadin migrates to LitElement, we'll probably convert this component as well, but we'll deal with this later.

**Comment by lkraav** [comment]
So looking at my screenshot above, and knowing that iron-star-rating does CSS magic to achieve half-stars, etc, we know for sure the added icon will be named `vaadin.star`.

**Comment by dominik-stypula-polcode** [comment]
@lkraav Should this be changed in `github:conversionxl/iron-star-rating` (iron-star-rating.js), or keep it in `cxl-star-rating` as overridden value?
```
          icon: {
              type: String,
              value: 'vaadin:star'
          },
```

**Comment by lkraav** [comment]
> keep it in cxl-star-rating as overridden value?

This :point_up: 

I think conversionxl/iron-star-rating should only have upstream-mergeable stuff, if possible.

**Comment by dominik-stypula-polcode** [comment]
@lkraav unless we make a pull request to the https://github.com/chadweimer/iron-star-rating and the author accepts the `vaadin:star` as default icon, and drops the whole `iron icons` package as `too bloated` if possible.

**Comment by lkraav** [comment]
> author accepts the vaadin:star as default icon

Mh? We will never propose vaadin:star as default icon into upstream. What's the confusion here?

**Comment by lkraav** [comment]
Forked iron-star-rating in https://github.com/conversionxl/aybolit/commit/b98a2d46cebce1dd2fa1316bd9fce3f4e1659b3f
