### ISSUE TITLE
cxl-section: wrap margin should have be overrideable via custom property

### ISSUE THREAD

**Issue by lkraav** [conversionxl/aybolit#94]
https://cxl.com/institute/pricing/ hero could use less space hogging, but cxl-section shadowed wrap doesn't allow an override.

Goal

![image](https://user-images.githubusercontent.com/147228/108500423-6b9e0880-72b8-11eb-803c-bfe43f783ba0.png)

**Comment by anoblet** [comment]
Not sure if this is what you're looking for?

https://github.com/anoblet/aybolit/pull/8/commits/7e1340d2be911aee4a7026aef5fa9c2016864c8c
