### ISSUE TITLE
Common Card component

### ISSUE THREAD

**Issue by heshfekry** [conversionxl/aybolit#96]
# 1. Global changes to the card

- [ ] Add tag - [use lumo styles font size M](https://cdn.vaadin.com/vaadin-lumo-styles/1.6.0/demo/typography.html) 
- [ ] Reduce Avater circle to 64px
- [ ] Change CTA to always `open`

## [2. Course cards](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=60%3A2)
![image](https://user-images.githubusercontent.com/72975440/108705188-46ee9e80-750d-11eb-806d-7e04c8e1180c.png)

- [ ] Show `Course` tag
- [ ] Tag colour is CXL red `lumo-primary-text-color: hsl(355.8, 74.7%, 48%);`

## [3. Minidegree cards](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=60%3A2)
![image](https://user-images.githubusercontent.com/72975440/108705217-4eae4300-750d-11eb-9926-34fa69083444.png)

- [ ] Show `Minidegree` tag
- [ ] Change colour to `var(--lumo-secondary-text-color)`

## [4. Hub cards](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=60%3A2)

![image](https://user-images.githubusercontent.com/72975440/108705232-55d55100-750d-11eb-857e-073fdb10f2c9.png)

- [ ] Show `Playbook hub` tag
- [ ] Change colour to `var(--lumo-secondary-text-color)`
- [ ] Link the title of the hub to the Title in the card
- [ ] If there is no title, then use the last level as title
- [ ] Show playbook and child hub count
- [ ] Show `section owner` (if exists), otherwise empty
- [ ] Show `about section` if exists, otherwise empty
- [ ] show the breadcrumb (up to 3 levels only, prioritize last)
- [ ] Show `open` CTA

## 5. [Playbook Cards](https://www.figma.com/file/kEdgO7kNJbkPBLMJ2YQFt0/CXL-Playbooks-(cxl-copy)?node-id=60%3A2)

![image](https://user-images.githubusercontent.com/72975440/108705266-5ff74f80-750d-11eb-9c54-a6c1cd1110ff.png)

- [ ] Show `Playbook` tag
- [ ] Tag colour is CXL red `lumo-primary-text-color: hsl(355.8, 74.7%, 48%);`
- [ ] Link the title of the playbook to the Title in the card
- [ ] Show total steps
- [ ] show  `author` followed by the `author name`
- [ ] show the breadcrumb (up to 3 levels only, prioritize last)
- [ ] Show `open` CTA

**Comment by lkraav** [comment]
There is no tag color strategy? When skimming, all red tags will look indistinguishable @zagyvalaszlo @heshfekry

**Comment by zagyvalaszlo** [comment]
Well, collections have a different color, so colors could differentiate playbooks / courses. The layouts of those already are a bit different. Not sure that introducing a secondary color would help here. That should then affect the whole playbooks/courses theme.
